### ISSUE TITLE
Separating preprocessed from raw data

### ISSUE THREAD

**Issue by jkbhagatio** [SainsburyWellcomeCentre/aeon_acquisition#100]
I'm using these definitions for "raw" and "preprocessed" data - what do you think?

> "raw" : any data that is bussed from a device directly to the acquisition computer. (note: this would mean that data that can be manipulated through device firmware settings (e.g. camera gain, exposure, etc.) is still considered raw)
> 
> "(pre)-processed": any data that is manipulated via software after being bussed to the acquisition computer (e.g. mouse position (from a camera device) and weight (from a scale device) data). (note: reading/loading raw data into different formats (e.g. bin, hex, int, etc.) is _not_ considered processing the data because the underlying data representation does not change).

I think we should move these types of data from `raw/` to `preprocessed/`

**Comment by glopesdev** [comment]
What about data compression? Is the compressed .avi file a preprocessed data stream?

The current working definition we were using was based more on reproducibility than data lines. Raw data is simply all data that we cannot reliably reconstruct offline. Conversely, preprocessed data is data that you can safely delete as long as you have code to recreate it.

This can be more complex than it seems and depends on agreeing on criteria for "reproducibility".

For example, position tracking data can in theory of course be extracted offline. However, because we compressed the raw video during acquisition, we don't actually have the same raw pixels offline than we had online, so the tracking result might be slightly different. This might be fine for most purposes, but as soon as we start using the online position data to make closed-loop decisions, the only way to understand why those decisions were made is to be able to reconstruct the online position data. If we can't do this offline, then the online positions might need to be considered "raw" data for logging purposes.

Another example was the filtering of weight data for the recent scale tests. In this case, I actually assumed incorrectly that all filtered data was simply processed data that could be reconstructed offline and recorded only the raw data from the scale. Turns out that the filters have a temporal component that is hard to reproduce offline, and so for accurately reproducing alert decisions we wanted to have the filtered weight recorded as well.

I suspect most data we will record online will be raw data in this sense. If some piece of data or stats can be reconstructed offline _and_ we don't use it for any closed-loop experiments, chances are high that we won't need to record it. So in principle the expectation would be that all acquired data is raw data.

**Comment by jkbhagatio** [comment]
> Raw data is simply all data that we cannot reliably reconstruct offline. Conversely, preprocessed data is data that you can safely delete as long as you have code to recreate it.

I see, ok yeah I'm happy with these definitions. 

For the specific cases of the current position and weight data though, is it possible these could be considered preprocessed according to these definitions? The video compression is lossless. For the filtered weight data, I forget - why is the temporal component hard to reproduce offline - is it possible at all? Maybe we can talk more about this tomorrow.

**Comment by glopesdev** [comment]
> The video compression is lossless. For the filtered weight data, I forget - why is the temporal component hard to reproduce offline - is it possible at all?

Unfortunately it's not possible to do lossless reconstruction in either case.

Video compression is not currently lossless, and making it so would likely increase our storage requirements by 5 or 10 times, so we might not want to go there, but happy to revisit this again.

Re. temporal component, the dependency comes from the fact that baselining of the scale data is based on position tracking, specifically when the ROI at the gate is activated. Due to the above video compression we might not reconstruct exactly the times of baselining from the video, and thus will not be possible to explain for example why a certain weight loss log message was sent at a certain time, etc.

Again, this is important only if we care about exact reconstruction, which might not be critical in all cases, but at least as we are defining it now, these two measures would be raw data.

Is there a reason why it matters whether a stream is stored in the raw or preprocessed? My original thinking is that everything you save online would be raw and thus immutable, whereas preprocessed you can delete whenever you need to. This might have implications to the structure of permissions in folders too, since my idea was that raw folder only has group read permissions, whereas preprocessed could have read/write permissions. It's simpler also for robocopy not to have to differentiate between two different folder structures.

Ideally between low-level and analysis APIs we should provide some way to abstract over whether a data stream is immutable or transient.

**Comment by jkbhagatio** [comment]
Ah my mistake, I forgot we are using fmp4 for video, and I see, I didn't realize the scale data baselining is based on position tracking rather than pixel diff motion detection.  

>Is there a reason why it matters whether a stream is stored in the raw or preprocessed?

No, I was just thinking that the position and weight data would be considered preprocessed data, but yeah I think it makes sense from this convo that they should be considered raw. I will add your definitions to the glossary : )

**Comment by jkbhagatio** [comment]
closing this as was settled last year.
