### ISSUE TITLE
Nuget Package is broken 

### ISSUE THREAD

**Issue by aspaNeuro** [SainsburyWellcomeCentre/aeon_acquisition#212]
The nuget package of AEON Acquisition 0.3.0 published in nuget.org has some dependencies that are not published so it doesn't install.
We should update it.
Current dependencies are:
Bonsai.Audio [2.7.0, )
Bonsai.Core [2.7.3, )
Bonsai.Design [2.7.1, )
Bonsai.Harp [3.4.0, )
Bonsai.Harp.Expander [0.1.0-build1534, )
Bonsai.Osc [2.7.0, )
Bonsai.Pylon [0.3.0, )
Bonsai.Scripting.Expressions [2.7.0, )
Bonsai.Sleap [0.2.0, )
Bonsai.Spinnaker [0.7.1-rc, )
Bonsai.System [2.7.1, )
Bonsai.Vision [2.7.0, )
Bonsai.ZeroMQ [0.2.0, )
LibGit2Sharp [0.25.4, )
MathNet.Numerics [4.5.1, )

**Comment by glopesdev** [comment]
The 0.3.0 version of the package depends on other pre-release versions available elsewhere. To resolve this we later switched to releasing all packages under "pre-release", and they shouldn't have this problem. We can't unfortunately change this specific package version since all NuGet packages are immutable and can't be deleted or replaced.
